# https://taskfile.dev

version: "3"

vars:
  MAIN_MODULE: backend:onboard-provider
  BACKEND_IMAGE_NAME: onboard-backend
  GRADLE_CMD: '{{if eq OS "windows"}}gradlew.bat{{else}}./gradlew{{end}}'

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list

  install:
    desc: "Install dependencies for all"
    deps: [deps]

  dev:
    desc: "Run Spring Boot Backend (Dev Profile)"
    cmds:
      - '{{.GRADLE_CMD}} --rerun-tasks :{{.MAIN_MODULE}}:bootRun --args="--spring.profiles.active=dev"'

  run:
    desc: "Run Spring Boot Backend (Default)"
    cmds:
      - "{{.GRADLE_CMD}} --rerun-tasks :{{.MAIN_MODULE}}:bootRun"

  test:
    desc: "Run Backend Tests"
    cmds:
      - "{{.GRADLE_CMD}} --rerun-tasks test"

  check:
    desc: "Run Backend quality checks (Spotless, Error Prone, SpotBugs, tests lifecycle)"
    cmds:
      - "{{.GRADLE_CMD}} --rerun-tasks check"

  format:
    desc: "Auto-format all Java code and Build scripts"
    cmds:
      - '{{.GRADLE_CMD}} --rerun-tasks spotlessApply'

  check-format:
    desc: "Verify code formatting (Fail if not formatted)"
    cmds:
      - '{{.GRADLE_CMD}} --rerun-tasks spotlessCheck'

  deps:
    desc: "Refresh Gradle Dependencies"
    cmds:
      - "{{.GRADLE_CMD}} --rerun-tasks --refresh-dependencies"

  verify:
    desc: "Full CI check: clean, build, and test everything"
    cmds:
      - "{{.GRADLE_CMD}} --rerun-tasks clean build"

  spotbugs:
    desc: "Run SpotBugs analysis for main and test classes"
    cmds:
      - "{{.GRADLE_CMD}} --rerun-tasks spotbugsMain spotbugsTest"

  checkstyle:
    desc: "Run Checkstyle for main and test sources"
    cmds:
      - "{{.GRADLE_CMD}} --rerun-tasks checkstyleMain checkstyleTest"

  checkstyle-main:
    desc: "Run Checkstyle for main sources"
    cmds:
      - "{{.GRADLE_CMD}} --rerun-tasks checkstyleMain"

  checkstyle-test:
    desc: "Run Checkstyle for test sources"
    cmds:
      - "{{.GRADLE_CMD}} --rerun-tasks checkstyleTest"

  docker-build:
    desc: "Build Backend Docker Image"
    cmds:
      - docker build -t {{.BACKEND_IMAGE_NAME}} -f Dockerfile .

  docker-run:
    desc: "Run Backend Docker Container"
    cmds:
      - docker run -p 8080:8080 {{.BACKEND_IMAGE_NAME}}
